### ISSUE TITLE
Keypress in search field problem

### ISSUE THREAD

**Issue by simonbcn** [sbondCo/Watcharr#169]
I just installed this app using [Truecharts on Truenas Scale](https://github.com/truecharts/charts/tree/master/charts/incubator/watcharr) and I like its simplicity but I have 2 drawbacks: 

1. When you are writing the search field, sometimes I have to press a key several times for it to display. I guess the continuous search process clutters the input.
2. I can't (or I haven't found a way) to mark in a multi-season series which ones I have seen and which ones I haven't seen.

**Comment by IRHM** [comment]
Hi @simonbcn, thank you for trying Watcharr and the feedback!

1. I haven't noticed anything like this before, are there any errors displayed in console (Ctrl+Shift+I) after having to re-type a letter to get the search to trigger?
    It may also be helpful if you could do a screen recording of the issue (including your browsers url bar).
2. Unfortunately that is not currently a feature, but it definitely sounds useful.

I created a new issue #170, to track (2) marking seasons as seen (i'll get to this asap for you tonight or tomorrow), I'll modify this issue to track the search bar issue.

**Comment by simonbcn** [comment]
This is the screen recording: https://dsc.cloud/f4287b/YQMUk2tcZFCXiFo2pH4EeHYObIVgrYPQY65oMqbXFX4JsIjjRjzs3JNE7Gh5rsUo62w5YLRDJgLTHr692DYto792v5LbCWRrVXwW.mov

I have to press some keys several times.

**Comment by IRHM** [comment]
@simonbcn Thank you for the video, helped out a lot. Turned out to be an issue with chrome specifically.

#171 seems to have fixed the issue (patch is live with latest dev version - testable on https://beta.watcharr.app).

I'll close the issue for now, but I can ping you when I get around to release the new version (ps I notice you are on v1.16.1, not sure how truecharts handles the version, but current latest is v1.20.0)

**Comment by IRHM** [comment]
Hi @simonbcn, this has just released in `v1.20.1` - if you have any other problems feel free to create another issue.

Thanks again for reporting this.
