### ISSUE TITLE
Allow filtering and sorting other watched lists

### ISSUE THREAD

**Issue by IRHM** [sbondCo/Watcharr#276]
We should allow filtering and sorting of other peoples watched lists.

**Comment by iamericfletcher** [comment]
If this is still unassigned, I'd like to give this a shot! I've got the project running locally on my Linux machine running Pop!_OS (Using Source instead of Docker for now). This will be my first time using `Go` and `Svelte` but I think I'm up for the task :)

I have all next week off from work so plan on studying the code base and coming up with a description of my approach to add here for review and discussion. 

Is this OK?

My first question is:

1. Do you have any recommendations for improving the development environment such that say changes to the front end trigger a reload on the server without having to rebuild? 

For example, say I change the below in `+page.svelte`:

`
    <h2>
      {#if login}
        Get Back In!
      {:else}
        Lucky You Found Us!
      {/if}
    </h2>
`

to:

`
    <h2>
      {#if login}
        Get Back In!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      {:else}
        Lucky You Found Us!
      {/if}
    </h2>
`

I'd like to then reload the server and see those changes reflected without having to rebuild. 

Is this possible? Also, apologies for what may seem like a beginner question! I hope it doesn't dissuade you from assigning the issue to me!

**Comment by IRHM** [comment]
Hi @iamericfletcher, thanks for taking an interest, that would be great!

Just to let you know, the filtering/sorting of your own watched list is all done client side (svelte/js), having a look at that existing code will surely help, I'm sure most of it can be reused.

Thanks again, if you need anything, feel free to let me know, I'm happy to help!

**Comment by iamericfletcher** [comment]
@IRHM - That's what I was thinking - that most of the existing filtering/sorting code can be reused :) A great first issue!

**Comment by IRHM** [comment]
@iamericfletcher, dont worry about it.

I dont have anything setup to rebuild the backend automatically, but for rebuilding the svelte code, running: `npm run dev` should setup a dev server with live reloading.

You can check out the package.json file for the other "scripts" that can be helpful during development (npm run <script name>).

**Comment by iamericfletcher** [comment]
Awesome - thanks so much and what an awesome project this is! Looking forward to coming up with a plan and perhaps some code for your review / feedback in the near future. 

Sincerely,
Eric

**Comment by IRHM** [comment]
Completed in #281, thanks!
