### ISSUE TITLE
UI Bug: WatchedStatus Tooltip Misalignment on Discover Content Page

### ISSUE THREAD

**Issue by iamericfletcher** [sbondCo/Watcharr#282]
**Description:**
When hovering over items in the PosterList on the Discover Content page, the PosterStatus tooltips appear misaligned relative to the items they are supposed to represent.

**Expected Behavior:**
The tooltips should be correctly aligned within each PosterList section (Trending Today, Trending Movies, Trending Shows, Upcoming Movies, and Upcoming Shows). 

**Steps to Reproduce:**

Navigate to Discover Content page on desktop
Scroll down a bit and then click and of the PosterStatus buttons
Observe the misalignment of the tooltip with respect to the item

Note that when scrolled all the way to the top, the tooltips align as they should. The misaligned surfaces only when scrolling down occurs. 

**Environment:**

- **Operating System:** Pop!_OS 22.04 LTS (Jammy)
- **Kernel:** Linux pop-os 6.6.6-76060606-generic (202312111032~1702306143~22.04~d28ffec SMP PREEMPT_DYNAMIC Mon D x86_64 GNU/Linux)
- **Browser:** Chrome version 120.0.0.0 (User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Safari/537.36)

**Video:**

https://github.com/sbondCo/Watcharr/assets/64165327/85b60b39-45a4-4d9e-ac73-d6ac8b5f7c04

**Comment by IRHM** [comment]
Hi @iamericfletcher, thank you for taking the time to report this bug! I appreciate the detailed report.

I noticed the same yesterday evening when I went to add a movie to my watched list, it seemed to happen on any page, wherever tooltips are used, if the page is scrolled.

This should hopefully be fixed in the `dev` branch by #277 - if you are able to check on dev you may be able to verify if it is working for you?

**Comment by iamericfletcher** [comment]
Agh! Yes - all fixed with tooltips showing as expected! I hadn't updated my fork with the changes from your upstream repository so was behind. It's all a learning experience for me!
