### ISSUE TITLE
Authentication: Add support for Plex/Jellyfin 

### ISSUE THREAD

**Issue by stephaje** [sbondCo/Watcharr#358]
It would be nice to allow users to log in using their Plex or Jellyfin account, to cut down on the number of credentials users need to manage. This can also lead to support for additional features down the road.

This is something that is supported by applications like [Jellyseerr](https://github.com/Fallenbagel/jellyseerr) and should be fairly straightforward to replicate.

**Comment by IRHM** [comment]
Hi @stephaje, Jellyfin has basic auth support already, though it requires an admin account to be made first through Watcharr and it to be configured in settings before you can login with any Jellyfin account on that server.

I have never interacted with Plex before, hopefully it can be added in, in a similar way.

**Comment by stephaje** [comment]
I'll start taking a look at this over the weekend and come back to you with a plan.

**Comment by stephaje** [comment]
Just leaving these here as references:
https://forums.plex.tv/t/authenticating-with-plex/609370
https://www.npmjs.com/package/plex-oauth

Helldivers has taken more out of my schedule this week than anticipated.

Integration with plex seems straightforward. Tying that into the local schema is the hard part. I'll have to spend more time thinking about if treating them as a user with their password being their plex access token is a good move, or if they should have an entirely separate table and handling. Input appreciated.

**Comment by IRHM** [comment]
I've been thinking the same lately whilst looking into a different task, slighly regretting making it like that. I don't think I looked far enough into the future.

A solution I thought up was to keep it half like it is, we could use the third party token fields for the way the user signs in (jellyfin or plex).

Then in the future, we could make a new UserServices table to store other service connections (for people who created their account with jellyfin auth, they could also connect plex?)

Not sure though, I don't see a scenario where someone would want to sign in via jellfin but also connect plex (and vice versa).

Might be best to enforce user can only be a jellyfin or plex user and can't mix both, because that would probably get really confusing on the server just to satify 0.2 peoples needs. (Then in future possibly make a way to convert user types)

Any thoughts² on my thoughts?

_p.s. thanks for the helldivers suggestion, got it last night after I saw your comment. Very fun 🦙_

**Comment by stephaje** [comment]
Ok, thoughts.

I've put some sloppy code [here](https://github.com/sbondCo/Watcharr/compare/dev...stephaje:Watcharr:plex-oauth-poc) just to see what we have to work with.

For sign-up via plex, I think we have a new server endpoint that only takes the authToken value and create a user with the username taken from the plex account metadata and the password being the authToken value. We also add a flag on the account that it was Plex generated for later.

For log-in when the local storage token isn't present, we have another new server endpoint that again only takes the authToken, fetches the plex account metadata, checks for an existing account that has the Plex generated flag, and updates the password to the new token.

Later we can pull the token from the password field to fetch more data from plex. (Edit: actually maybe not? I assume the passwords are hashed. If they are, we can just do a token table separately) The password also protects all the current flows/apis. Users don't ever need to know it, and it will change any time their session expires, so they won't be able to use the basic auth based APIs, but the enhancement for that will cover it.

For Plex AND Jellyfin, I agree mixing them is difficult, but possible. I don't think this blocks the possibility in the future, because a user who is OAuthing via Plex should always treat Plex as the primary service and then Jellyfin would be a secondary service they configure on top of that account.

If that all sounds good, I'll continue working on this. If you want to message me about it, I set up a matrix account: `@jesii:matrix.org`

P.S. wonder if we should try and get the pop up to render in a modal object? Idk how this works on mobile without more testing.

**Comment by stephaje** [comment]
I ended up not being able to get it off my mind and finished 95% of it. I've left a couple comments on there to start some discussion, but IMO I think it's pretty close to done at this point.

**Comment by stephaje** [comment]
I think this can be closed, but idk how/if I can tie it to the PR first.

**Comment by IRHM** [comment]
> I think this can be closed, but idk how/if I can tie it to the PR first.

Hey, forgot about the issue. Linked to your PR, will close now.

I was thinking about making a public Matrix chat for anyone with questions, may make that and add you if possible when I get around to it.
