### ISSUE TITLE
Can no longer build off dev branch

### ISSUE THREAD

**Issue by stephaje** [sbondCo/Watcharr#384]
The application does not appear to work for me from a fresh dev pull.

This is my init script:
```
cd ~/Watcharr

rm -rf ./server/ui
npm i && npm run build && mv ./build ./server/ui

cd server
rm -f ./watcharr
go mod download && GOOS=linux go build -o ./watcharr

sleep 3; xdg-open http://localhost:3000 &
./watcharr
```

The application output is

```
time=2024-03-01T18:03:45.809-06:00 level=INFO msg="Watcharr Starting"
time=2024-03-01T18:03:45.810-06:00 level=INFO msg="Logging level set" logging_level=INFO
time=2024-03-01T18:03:45.814-06:00 level=INFO msg="No users found.. creating setup routes."
time=2024-03-01T18:03:45.814-06:00 level=ERROR msg="IGDB init client id and or secret not provided"
Listening on 0.0.0.0:3000
WATCHARR v1.34.0
```

The landing page immediately redirects to http://localhost:3000/login?again=1 and any time I try to log in or create a new user, the server log adds a new `WATCHARR v1.34.0` line.

I've tried clearing my cache/private window/manually deleting server data, but no success.

**Comment by IRHM** [comment]
Hi @stephaje, sorry you're having trouble with this.

Something is definitely wrong, I tried it out myself and get the same issue, though strangely it seems to work when built in a docker container.

Looks like it might not be registering its routes properly (I get 404s from the ui to any /api requests ~and no logs saying its created them~).

I'll keep looking into this and try to get it working, will let you know.

**Comment by IRHM** [comment]
Oh @stephaje, I should have read [my own guide](https://watcharr.app/docs/installation/from-source) more thoroughly, we have to go to `http://localhost:3080`.

Let me know if that works for you.

Sorry for the confusion if it does, the log in console that says `Listening on 0.0.0.0:3000` is for the UI server, which when started through the backend (in production mode), needs to be accessed through the backend (otherwise api requests on the client will try to go to the wrong address).

**Comment by stephaje** [comment]
Yeah @IRHM, that was it. I had an inkling it was on me, but I just could not figure it out yesterday. I'll take a look at updating the startup logging to also call out :3080 as I start prototyping the Plex Oauth stuff today.
