### ISSUE TITLE
Unraid support

### ISSUE THREAD

**Issue by mayberts** [sbondCo/Watcharr#410]
Could this be made available on unraid? It would be good to run it with the other arr apps

**Comment by IRHM** [comment]
Hi @mayberts thanks for opening an issue, I haven't used unraid before, but I can definitely see what we can do for you.

Would you like to see it as a community app (forgive me if thats a dumb question)?

I'll see if I can test it out in a virtual machine.

**Comment by mayberts** [comment]
> Hi @mayberts thanks for opening an issue, I haven't used unraid before, but I can definitely see what we can do for you.
> 
> Would you like to see it as a community app (forgive me if thats a dumb question)?
> 
> I'll see if I can test it out in a virtual machine.

Community app best, I'd imagine the rest of the unraid community would use it too.

Happy to help with testing, if needed

**Comment by mayberts** [comment]
I have added the container manually so I can have a look and test. For anyone else who would like to add it manually. Click the docker tab in the unraid UI and then click add container.  this is how my config looks 
![image](https://github.com/sbondCo/Watcharr/assets/27490448/9e120e81-647d-46fd-8def-9880416bae95)

**Comment by IRHM** [comment]
Hey @mayberts, thanks for sharing that configuration.

I tried to get unraid setup so I could create a template, but unfortunately I'm not going to get past setting it up. Looks like it wants me to create an array before I can access that docker template page, but since I have no idea what I'm doing, I don't want to select my only main drive and break everything and die.

Might be best if I leave this for a more experienced person to create and publish. I don't mind setting up a repository for the xml templates and giving access to whoever can help (or feel free to make your own repo if you'd like to maintain it yourself).

This is the guide I was trying to follow: https://forums.unraid.net/topic/57181-docker-faq/#comment-566084

We have icons in this folder if anyone does set it up: https://github.com/sbondCo/Watcharr/tree/dev/static - I think this is probably the nicest logo: https://github.com/sbondCo/Watcharr/blob/dev/static/logo-sqre.png

Anyhow, hopefully it's working for you with that setup.

**Comment by mayberts** [comment]
If you don't mind hosting the XML, I will follow up with the rest. If not I will continue with my current setup. It's just the section under `Publishing to CA` that needs to be done now 

XML is in the zip file
[Watcharr.zip](https://github.com/sbondCo/Watcharr/files/14598012/Watcharr.zip)

**Comment by IRHM** [comment]
Thanks a lot @mayberts, I'll try to finish the rest of the guide in a short while.

Edit: Just waiting on a reply from the head squid now.

**Comment by IRHM** [comment]
Sorry for how long this is taking, still waiting on a reply. Not sure how long this usually takes for a response.

**Comment by NibblesOnGithub** [comment]
> If you don't mind hosting the XML, I will follow up with the rest. If not I will continue with my current setup. It's just the section under `Publishing to CA` that needs to be done now
> 
> XML is in the zip file [Watcharr.zip](https://github.com/sbondCo/Watcharr/files/14598012/Watcharr.zip)

This is exactly what I needed, thank you so much for this! Working flawlessly. I wonder if Squid (iirc that's who manages CA) is just super backlogged or something.

**Comment by IRHM** [comment]
Yep could be if only he does them, hopefully it's added soon!

**Comment by IRHM** [comment]
Just been added by Squid, should hopefully be in the community apps now. Let me know if there are any issues with it!

![image](https://github.com/sbondCo/Watcharr/assets/37304121/6f0b1eea-d813-411c-9aa4-fc4efaa7b5ae)
