### ISSUE TITLE
Incorrect streaming channel(s)

### ISSUE THREAD

**Issue by pecbeck** [sbondCo/Watcharr#477]
Hi

Streaming channels are sometimes incorrect. Example is Blue Lights, shown on BBC ,and shown as BBC on tvdb, is showing as britbox, appletv etc on watcharr

**Comment by IRHM** [comment]
Hey @pecbeck, thanks for bringing up this issue.

It should be mostly fixed by a PR just merged yesterday (#463) that lets you set your region. I believe it is showing britbox/appletv for you, because those are available in the US, but I'm guessing you want providers for the UK region (this should work in the next version, letting you pick a region)?

Testing with the changes in that PR, I've noticed, we only display Sky Go, I'll have to fix that so it also shows free providers (BBC iPlayer comes through as a `free` provider from themoviedb api).

Thanks again, I'll get to this soon!

**Comment by IRHM** [comment]
Thanks again! Lookout for the next version, hopefully will be released soon for you to try.

When testing, in UK region, this show will now have sky and bbc iplayer showing as providers:

![image](https://github.com/sbondCo/Watcharr/assets/37304121/3d8efaab-0b11-4c69-982b-3bf6d50797f3)
