### ISSUE TITLE
Watcharr doesn't found this movie: "Domingo Domingo"

### ISSUE THREAD

**Issue by simonbcn** [sbondCo/Watcharr#531]
```
Watcharr v1.39.0 running on Docker
```

When I search for the movie "[_Domingo Domingo_](https://www.themoviedb.org/movie/874511-domingo-domingo)", Watcharr doesn't show that movie:
![Captura de pantalla 2024-05-29 a las 13 33 53](https://github.com/sbondCo/Watcharr/assets/428231/c9db2798-da93-4f37-83c9-a778f179c4d6)

In fact, I would say that there is a problem with the search results because if I put only "_Sunday_" it shows this:
![Captura de pantalla 2024-05-29 a las 13 36 53](https://github.com/sbondCo/Watcharr/assets/428231/cbf7afa4-ee22-4074-8372-320cd0ad6d82)

**Comment by IRHM** [comment]
Hi, sorry you're having this problem.

I think this is because we only show the first page of results, but TMDB seems to show a bunch of people in the results instead of the movie with the exact name.

I believe this is the movie you're looking for? https://www.themoviedb.org/movie/874511-domingo-domingo

For now, you may have to directly visit it in your watcharr instance by id in url: 874511

https://beta.watcharr.app/movie/874511

(Replacing beta.watcharr.app with your servers hostname/address).

I will look into this when I get a chance, we will probably have to add support for pagination (showing next page results when scrolling down results).

Thanks for making this issue!

**Comment by IRHM** [comment]
Support for infinite scrolling (pagination) has been added and I've reworked the movie/tv/people filter button at the top of results to always be shown and to perform a new request to the server to get all content of that type.

Both methods should work to help you find any piece of content you are looking for. I tested for this case, I can either scroll down until I see this movie, or I click the `movies` filter and see it right there.

Will be released soon!
