### ISSUE TITLE
Ability to pin a season would be great

### ISSUE THREAD

**Issue by n00b12345** [sbondCo/Watcharr#602]
For shows which have many seasons, it can be a little difficult to navigate to episodes in, say, season 5 which I may be watching. Doing this for every episode repeatedly can be a little annoying.

The ability to pin a season (within a show) so that every time the show page is opened, the pinned season shows up instead of season 1, would be great to have.

**Comment by IRHM** [comment]
Hi @n00b12345, that is a good idea, I wonder what you think about these two alternative implementations:

1. Whenever you click on a season tab, we save that and always preload that season whenever you click into that show again (we could save it locally, so it can be different on each device, or we can save it to the server so it preloads the same season for all your devices) or;
2. The client can look at the most recent episode/season that was marked as watching/finished and preload that season.

I think one of these solutions may be nicer than manually pinning a season(?), since you wouldn't have to change your pin after every season. What do you think?

**Comment by n00b12345** [comment]
> Hi @n00b12345, that is a good idea, I wonder what you think about these two alternative implementations:
> 
> 1. Whenever you click on a season tab, we save that and always preload that season whenever you click into that show again (we could save it locally, so it can be different on each device, or we can save it to the server so it preloads the same season for all your devices) or;
> 2. The client can look at the most recent episode/season that was marked as watching/finished and preload that season.
> 
> I think one of these solutions may be nicer than manually pinning a season(?), since you wouldn't have to change your pin after every season. What do you think?

This is absolutely better than pinning. I love solution 1.

Personally, I would prefer that the season data be saved on the server. That way all devices will open the same season page.

Thank you, as always 👍
