### ISSUE TITLE
Feature: Import of TodoMovies

### ISSUE THREAD

**Issue by AlexPerathoner** [sbondCo/Watcharr#613]
I've been using TodoMovies (https://todomovies.app/) to track my watch list and wanted to switch to Watcharr. I've noticed that there isn't an option for importing the csv exported by such app and I'm willing to look into implementing it myself.

I've noticed in CONTRIBUTING you suggest discussing PRs first, so here we are: is this something you'd be happy to find added? Anything I should pay attention to?

Related to #429

**Comment by IRHM** [comment]
Hi @AlexPerathoner, thank you for opening this issue and thanks for offering to work on it, that would be great!

If it's just a generic csv file exported from TodoMovies, then you could likely copy some of the code used for other importing methods and change it around to work with the specific csv format from TodoMovies.

For importing files, the current process is goes like so: drop file into watcharr, the client parses it and displays the content in a table, then the user starts the import and a generic import route is called for each show/movie with the relevant data to complete the import.

This rough guide should help you get started:
1. Add a new button for TodoMovies and make it go to a new function which reads the csv and stores its data in [import/+page.svelte](https://github.com/sbondCo/Watcharr/blob/dev/src/routes/(app)/import/%2Bpage.svelte).
2. Get the loaded file data and parse it so that it conforms to the `ImportedList[]` type (adds to rList variable) in [import/process/+page.svelte](https://github.com/sbondCo/Watcharr/blob/dev/src/routes/(app)/import/process/%2Bpage.svelte).
3. The start import button should work now on the process page under the populated table.

Hopefully that helps you out and it goes smoothly. You should be able to just copy one of the functions in those files and change them around for this app.

Let me know if you have any questions! Thanks!

Oh and p.s. the package `papaparse` for parsing csv is already a dependency for the client, so you could use that straight away: https://www.papaparse.com/docs (theres existing function calls that parse csv in those import files too if you want to copy them over)

**Comment by AlexPerathoner** [comment]
Thanks, much more detailed instructions that I could've hoped for.
How did you create the svg icons? Did you generate them with a particular tool or did you do it by hand?

**Comment by AlexPerathoner** [comment]
Some updates:
- The import function itself works, but I've found out that the exported `.csv` is missing some info, which a custom backup file (`.todomovieslist`, but it's really just a json so it shouldn't be a problem) has: the date it was added, and also custom lists it has been added to. If it's okay I'd switch to using that backup file instead of the csv, and parse the custom lists into tags.
- While importing, only name, year and type are shown. The year is quite complicated to parse - is that necessary or is it only to help find the right movie? A `tmdbID` is already present, so I guess it doesn't make any difference if it's set or not(?)... since movies in both status `FINISHED` and `PLANNED` can be added, should I also add a dropdown that shows that? Is some issues for that perhaps already in progress?

**Comment by IRHM** [comment]
Hey @AlexPerathoner thanks for the updates:

1. I just take the icons from the respective project, that should be okay.
2. Yeah that is fine, should be easier for you if its JSON. I don't think the generic /import route supports adding the movie/show to a tag, you could add support for it or just use the create tag/add to tag routes directly instead.
3. You're right, if you have the tmdbId, then you don't have to bother with setting the year (that just helps if searching only via name of content).
You don't have to bother with adding a dropdown, I would think anyone importing would just let the logic decide based on their export.
